// ===== Conteúdo educativo e perguntas do quiz — MISSÃO CIBERSEGURANÇA =====
// HISTORY, QUIZ_TIPS, QUIZ_ARTICLE, QUIZ_BY_THEME
// Alinhado por artIdx (0-19), na mesma ordem lógica original do jogo.

export const HISTORY = [
  {
    title: "🌐 Nasce a Internet",
    // BUG CORRIGIDO: dizia "A World Wide Web foi criada em 1989... [logo
    // depois do título] Nasce a Internet" — confundindo a Internet (a rede
    // global de computadores, que já existia desde 1969, com a ARPANET) com
    // a World Wide Web (o sistema de páginas com links criado por Tim
    // Berners-Lee só 20 anos depois, em 1989). São coisas diferentes: a Web
    // é um serviço que corre POR CIMA da internet, não a internet em si.
    text: "A Internet nasceu em 1969, quando os primeiros computadores foram ligados em rede (a ARPANET). Só 20 anos depois, em 1989, é que o cientista Tim Berners-Lee criou a World Wide Web — as páginas com links que hoje usamos para navegar. Essa ligação global trouxe também novos riscos. A cibersegurança é o conjunto de práticas que nos protege quando usamos computadores, telemóveis e a internet."
  },
  {
    title: "🔐 Palavras-passe Fortes",
    text: "Uma palavra-passe forte combina letras maiúsculas, minúsculas, números e símbolos, e não usa dados óbvios como o teu nome ou data de nascimento. A verificação em dois passos (2FA) acrescenta uma segunda camada de proteção, mesmo que alguém descubra a tua palavra-passe."
  },
  {
    title: "🪪 Não Partilhes Dados Pessoais",
    text: "Nome completo, morada, telefone, escola ou palavras-passe nunca devem ser partilhados online com desconhecidos. Estes dados podem ser usados para te localizar ou enganar. Guarda-os só para ti e para as pessoas de confiança."
  },
  {
    title: "🆘 Quem Nos Protege Online",
    text: "Em Portugal, o Centro Nacional de Cibersegurança (CNCS) e o projeto SeguraNet ajudam crianças e escolas a navegar em segurança. A Linha Internet Segura (800 21 90 90) e o site internetsegura.pt apoiam quem tiver um problema online."
  },
  {
    title: "🦠 Vírus e Malware",
    text: "Um vírus informático é um programa malicioso que se espalha e pode danificar ficheiros ou roubar informação. Um antivírus atualizado, e nunca instalar programas de fontes desconhecidas, ajudam a manter o computador saudável."
  },
  {
    title: "🎮 Jogar em Segurança",
    text: "Os jogos online têm classificações etárias (como o sistema PEGI) que indicam para que idades são adequados. Em jogos com chat, nunca se deve combinar encontros com desconhecidos nem partilhar dados pessoais, mesmo que pareçam simpáticos."
  },
  {
    title: "👣 A Tua Pegada Digital",
    text: "Tudo o que publicas online deixa um rasto — a chamada 'pegada digital' — que pode durar para sempre, mesmo depois de apagares a publicação. Por isso vale sempre a pena pensar antes de publicar."
  },
  {
    title: "📰 Notícias Falsas (Fake News)",
    text: "Fake news são notícias falsas ou enganosas espalhadas online, muitas vezes para causar confusão. Para as identificar: verifica a fonte, procura a mesma notícia noutros meios credíveis e desconfia de títulos muito chocantes."
  },
  {
    title: "🎣 Reconhece o Phishing",
    text: "Phishing é quando alguém finge ser uma entidade de confiança (um banco, uma escola, um amigo) para te enganar e roubar palavras-passe ou dados. O sinal mais claro é um link ou pedido urgente e suspeito — nunca clicar e avisar sempre um adulto."
  },
  {
    title: "💻 Cuida dos Teus Dispositivos",
    text: "Manter o sistema operativo e as aplicações sempre atualizadas fecha falhas de segurança que os atacantes podem explorar. Evitar iniciar sessão em contas importantes através de redes Wi-Fi públicas também protege os teus dados."
  },
  {
    title: "👨‍👩‍👧 Regras de Ecrã em Família",
    text: "Combinar com os pais ou encarregados de educação regras claras sobre tempo de ecrã, que aplicações podem ser usadas e o que fazer se algo correr mal online ajuda a criar hábitos digitais saudáveis desde cedo."
  },
  {
    title: "📶 Cuidado com o Wi-Fi Público",
    text: "As redes Wi-Fi públicas (cafés, centros comerciais) muitas vezes não são seguras. Evita fazer login em contas com dados sensíveis quando estiveres ligado a uma rede pública, e desativa a ligação automática a redes desconhecidas."
  },
  {
    title: "💾 Faz Cópias de Segurança",
    text: "Guardar cópias dos teus trabalhos e ficheiros importantes numa pen ou na nuvem protege-te contra a perda de dados por avarias, vírus ou acidentes. É um hábito simples que evita muitos disgostos."
  },
  {
    title: "♿ Tecnologia para Todos",
    text: "Ferramentas como leitores de ecrã, legendas automáticas e comandos por voz tornam a tecnologia acessível a crianças com diferentes necessidades. A acessibilidade digital garante que ninguém fica de fora do mundo online."
  },
  {
    title: "🛒 Spam e Compras Seguras",
    text: "Spam são mensagens indesejadas, muitas vezes com publicidade enganosa ou ofertas boas demais para ser verdade. Antes de comprar algo online, confirma se o site é oficial e nunca partilhes dados do cartão em páginas suspeitas."
  },
  {
    title: "📢 Denuncia e Pede Ajuda",
    text: "Todas as plataformas têm um botão de denúncia para reportar conteúdos ou comportamentos impróprios. Usar esse botão, e falar sempre com um adulto de confiança, é um direito e um dever de qualquer utilizador da internet."
  },
  {
    title: "🧑‍💻 A Tua Identidade Digital",
    text: "A maioria das redes sociais (Instagram, TikTok, YouTube) exige, no mínimo, 13 anos para criar conta. Um perfil privado limita quem pode ver as tuas publicações a pessoas que tu aprovaste."
  },
  {
    title: "🔒 Respeita a Privacidade",
    text: "Respeitar a privacidade é não partilhar fotos ou informações de amigos e familiares sem autorização, e manter as tuas próprias contas privadas. A privacidade online, tal como offline, é um direito de todos."
  },
  {
    title: "🚫 Cuidado com Desconhecidos",
    text: "Nunca deves aceitar pedidos de amizade de desconhecidos nem responder a mensagens que peçam informações pessoais ou fotografias. Se alguém insistir ou te fizer sentir desconfortável, conta sempre a um adulto de confiança."
  },
  {
    title: "⚖️ Direitos e Deveres Digitais",
    text: "Desde 2021 que a ONU reconhece que todos os direitos das crianças se aplicam também ao mundo digital — incluindo privacidade e proteção. Mas com direitos vêm deveres: usar a internet com responsabilidade e respeito por todos."
  }
];

export const QUIZ_TIPS = {
  historia_internet:      "A Internet nasceu em 1969; a World Wide Web (as páginas com links) surgiu 20 anos depois, em 1989. A cibersegurança protege-te sempre que as usas.",
  palavras_passe:         "Usa letras, números e símbolos numa palavra-passe forte, e ativa a verificação em dois passos (2FA).",
  dados_pessoais:         "Nunca partilhes nome completo, morada, telefone ou palavras-passe com desconhecidos online.",
  instituicoes_apoio:     "Em Portugal, a Linha Internet Segura (800 21 90 90) e o SeguraNet ajudam com problemas online.",
  virus_malware:          "Um antivírus atualizado e nunca instalar programas de fontes desconhecidas protegem o computador.",
  jogos_seguros:          "As classificações etárias (PEGI) indicam a idade recomendada para cada jogo — respeita-as.",
  pegada_digital:         "Tudo o que publicas deixa um rasto digital que pode durar para sempre — pensa antes de publicar.",
  fake_news:              "Para identificar fake news: verifica a fonte, procura noutros meios e desconfia de títulos chocantes.",
  phishing:               "O phishing finge ser alguém de confiança para roubar os teus dados — nunca clicar em links suspeitos.",
  dispositivos:           "Manter tudo atualizado e evitar contas importantes em Wi-Fi público protege os teus dispositivos.",
  regras_familia:         "Combinar regras de ecrã e de uso da internet com a família cria hábitos digitais saudáveis.",
  wifi_publico:           "Em redes Wi-Fi públicas, evita fazer login em contas com dados sensíveis.",
  copias_seguranca:       "Guardar cópias dos teus ficheiros numa pen ou na nuvem protege-te contra a perda de dados.",
  acessibilidade_digital: "Leitores de ecrã, legendas e comandos de voz tornam a tecnologia acessível a todos.",
  spam_compras:           "Desconfia de ofertas boas demais para ser verdade e confirma sempre se um site é oficial antes de comprar.",
  denuncia_conteudo:      "Usa o botão de denúncia das plataformas e fala sempre com um adulto de confiança se algo correr mal.",
  identidade_digital:     "A maioria das redes sociais exige, no mínimo, 13 anos — e um perfil privado protege as tuas publicações.",
  privacidade:            "Não partilhes fotos de outras pessoas sem autorização, e mantém as tuas contas privadas.",
  contacto_desconhecidos: "Nunca aceites pedidos de desconhecidos nem partilhes dados pessoais com quem não conheces.",
  direitos_digitais:      "Desde 2021, os direitos das crianças aplicam-se também ao mundo digital — com direitos vêm deveres."
};

export const QUIZ_ARTICLE = {
  historia_internet:      null,
  palavras_passe:         "Dica 1",
  dados_pessoais:         "Dica 2",
  instituicoes_apoio:     "800 21 90 90",
  virus_malware:          null,
  jogos_seguros:          "PEGI",
  pegada_digital:         "Dica 3",
  fake_news:              null,
  phishing:               "Dica 4",
  dispositivos:           "Dica 6",
  regras_familia:         null,
  wifi_publico:           null,
  copias_seguranca:       "Dica 7",
  acessibilidade_digital: null,
  spam_compras:           null,
  denuncia_conteudo:      "Dica 8",
  identidade_digital:     null,
  privacidade:            "Dica 5",
  contacto_desconhecidos: null,
  direitos_digitais:      null
};

export const QUIZ_BY_THEME = {
  historia_internet: [
    { q:"Quem criou a World Wide Web e em que ano?", a:[{t:"Tim Berners-Lee, em 1989",ok:true},{t:"Bill Gates, em 1975",ok:false},{t:"Steve Jobs, em 2001",ok:false}], exp:"Tim Berners-Lee criou a World Wide Web em 1989, permitindo ligar documentos através de hiperligações — a base da internet que usamos hoje." },
    { q:"O que significa 'cibersegurança'?", a:[{t:"O conjunto de práticas que protegem pessoas e dados no mundo digital",ok:true},{t:"Um tipo de vírus informático",ok:false},{t:"Uma marca de computadores",ok:false}], exp:"Cibersegurança é o conjunto de práticas, ferramentas e hábitos que protegem computadores, telemóveis, dados e pessoas dos riscos do mundo digital." },
    { q:"Porque é importante aprender cibersegurança desde criança?", a:[{t:"Porque cada vez mais crianças usam a internet e a tecnologia no dia a dia",ok:true},{t:"Só é importante para adultos que trabalham com computadores",ok:false},{t:"Não é importante, só os hackers precisam de saber",ok:false}], exp:"As crianças usam cada vez mais dispositivos e a internet para estudar e brincar, por isso aprender a proteger-se online é tão importante como aprender regras de segurança no mundo real." },
    { q:"O que é a internet?", a:[{t:"Uma rede mundial que liga milhões de computadores e dispositivos entre si",ok:true},{t:"Um programa que só existe num computador",ok:false},{t:"Um tipo de jogo de vídeo",ok:false}], exp:"A internet é uma rede global que liga computadores e dispositivos em todo o mundo, permitindo partilhar informação, comunicar e aceder a serviços." },
    { q:"Qual destes é um exemplo de bom hábito de cibersegurança?", a:[{t:"Pensar antes de clicar e antes de partilhar informação",ok:true},{t:"Clicar em tudo o que aparece no ecrã",ok:false},{t:"Partilhar a palavra-passe com todos os amigos",ok:false}], exp:"Pensar antes de agir — antes de clicar num link, instalar algo ou partilhar dados — é a base de todos os bons hábitos de cibersegurança." },
    { q:"Em que ano nasceu a Internet, quando os primeiros computadores foram ligados em rede pela ARPANET?", a:[{t:"Em 1969",ok:true},{t:"Em 1989",ok:false},{t:"Em 2000",ok:false}], exp:"A Internet nasceu em 1969, com a ARPANET, a rede que ligou os primeiros computadores universitários nos Estados Unidos. A World Wide Web só surgiu 20 anos depois, em 1989." },
    { q:"Qual foi a primeira mensagem alguma vez enviada entre dois computadores em rede, em 1969?", a:[{t:"\"LO\" — o sistema falhou a meio da palavra \"LOGIN\"",ok:true},{t:"\"OLÁ MUNDO\"",ok:false},{t:"A palavra completa \"LOGIN\", sem qualquer problema",ok:false}], exp:"Em 29 de outubro de 1969, investigadores tentaram enviar a palavra \"LOGIN\" entre a Universidade da Califórnia em Los Angeles e o Instituto de Pesquisa de Stanford, mas o sistema falhou a meio — só chegaram as letras \"L\" e \"O\"." },
    { q:"O que significa a sigla \"WWW\", que aparece no início de muitos endereços de sites?", a:[{t:"World Wide Web",ok:true},{t:"World Wide Wire",ok:false},{t:"Web World Window",ok:false}], exp:"WWW significa World Wide Web (\"teia mundial\"), o sistema de páginas ligadas por hiperligações criado por Tim Berners-Lee em 1989." },
    { q:"Qual a diferença entre a Internet e a World Wide Web?", a:[{t:"A Internet é a rede global de computadores; a Web é um serviço que funciona por cima dela",ok:true},{t:"São exatamente a mesma coisa, só com nomes diferentes",ok:false},{t:"A Web é mais antiga do que a Internet",ok:false}], exp:"A Internet (desde 1969) é a rede que liga computadores; a World Wide Web (desde 1989) é um dos serviços que corre por cima dessa rede — as páginas com links que usamos para navegar." },
    { q:"Que instituições foram ligadas pela primeira vez através da ARPANET, em 1969?", a:[{t:"A Universidade da Califórnia em Los Angeles (UCLA) e o Instituto de Pesquisa de Stanford",ok:true},{t:"A Universidade de Harvard e o MIT",ok:false},{t:"Duas universidades portuguesas",ok:false}], exp:"A primeira ligação da ARPANET juntou um computador da UCLA a outro do Instituto de Pesquisa de Stanford (SRI), na Califórnia — o primeiro passo da rede que se tornaria a Internet." },
    { q:"Quantos computadores (nós) faziam parte da ARPANET no final de 1969?", a:[{t:"4",ok:true},{t:"400",ok:false},{t:"40 mil",ok:false}], exp:"No final de 1969, a ARPANET ligava apenas 4 computadores, em quatro universidades norte-americanas. Hoje, milhares de milhões de dispositivos estão ligados à Internet em todo o mundo." },
    { q:"Que tipos de dispositivos protege a cibersegurança?", a:[{t:"Computadores, telemóveis, tablets e qualquer outro dispositivo ligado à Internet",ok:true},{t:"Só computadores de secretária",ok:false},{t:"Só telemóveis muito recentes",ok:false}], exp:"A cibersegurança protege qualquer dispositivo que se ligue a redes ou à Internet — computadores, telemóveis, tablets, consolas de jogos e muitos outros." },
    { q:"O que é uma \"rede de computadores\"?", a:[{t:"Um conjunto de computadores ligados entre si, capazes de trocar informação",ok:true},{t:"Um único computador muito potente",ok:false},{t:"Um programa que serve para desenhar",ok:false}], exp:"Uma rede de computadores é um conjunto de dispositivos ligados entre si que podem comunicar e trocar informação — a Internet é a maior rede de computadores do mundo, ligando milhares de milhões de dispositivos." }
  ],
  palavras_passe: [
    { q:"O que torna uma palavra-passe forte?", a:[{t:"Combinar letras maiúsculas, minúsculas, números e símbolos",ok:true},{t:"Usar só o teu nome próprio",ok:false},{t:"Usar sempre '123456'",ok:false}], exp:"Uma palavra-passe forte mistura vários tipos de carateres e evita informação óbvia, como o teu nome, para ser mais difícil de adivinhar." },
    { q:"O que é a verificação em dois passos (2FA)?", a:[{t:"Um segundo código, além da palavra-passe, para confirmar que és mesmo tu",ok:true},{t:"Escrever a palavra-passe duas vezes seguidas",ok:false},{t:"Ter duas palavras-passe iguais em contas diferentes",ok:false}], exp:"A 2FA pede um segundo código (por exemplo, enviado por SMS ou app) além da palavra-passe, tornando muito mais difícil alguém entrar na tua conta mesmo que descubra a palavra-passe." },
    { q:"Deves usar a mesma palavra-passe em todas as tuas contas?", a:[{t:"Não — se uma conta for descoberta, todas as outras ficam em risco",ok:true},{t:"Sim, assim é mais fácil de memorizar",ok:false},{t:"Sim, desde que seja muito longa",ok:false}], exp:"Usar palavras-passe diferentes em cada conta significa que, mesmo que uma seja descoberta, as restantes continuam protegidas." },
    { q:"O que deves fazer com a tua palavra-passe?", a:[{t:"Mantê-la em segredo, mesmo dos amigos mais próximos",ok:true},{t:"Partilhá-la com o melhor amigo, para ele guardar",ok:false},{t:"Escrevê-la num papel colado ao ecrã do computador",ok:false}], exp:"A palavra-passe deve ser sempre pessoal e secreta — partilhá-la, mesmo com amigos de confiança, aumenta o risco de alguém aceder à tua conta." },
    { q:"Porque é arriscado usar a data de nascimento como palavra-passe?", a:[{t:"Porque é uma informação fácil de descobrir sobre ti",ok:true},{t:"Porque é demasiado longa para memorizar",ok:false},{t:"Não é arriscado, é uma boa escolha",ok:false}], exp:"Datas de nascimento, nomes ou moradas são fáceis de descobrir online, tornando a palavra-passe mais fácil de adivinhar." },
    { q:"O que é um \"gestor de palavras-passe\"?", a:[{t:"Uma aplicação que guarda e ajuda a criar palavras-passe seguras",ok:true},{t:"Um vírus que rouba palavras-passe",ok:false},{t:"Uma rede social só para adultos",ok:false}], exp:"Um gestor de palavras-passe é uma aplicação que guarda as tuas palavras-passe de forma encriptada e pode ajudar a criar palavras-passe fortes e diferentes para cada conta." },
    { q:"Em geral, uma palavra-passe mais longa é...", a:[{t:"Mais difícil de adivinhar ou descobrir",ok:true},{t:"Sempre mais fraca",ok:false},{t:"Irrelevante para a segurança",ok:false}], exp:"Quanto mais longa for uma palavra-passe, mais combinações um atacante teria de tentar para a descobrir — por isso o comprimento ajuda a torná-la mais segura." },
    { q:"Qual destas é claramente uma palavra-passe fraca?", a:[{t:"\"123456\"",ok:true},{t:"Uma frase longa com letras, números e símbolos misturados",ok:false},{t:"Uma combinação aleatória de vários carateres",ok:false}], exp:"\"123456\" está entre as palavras-passe mais usadas e mais fáceis de adivinhar do mundo — deve ser sempre evitada." },
    { q:"Onde NÃO deves escrever a tua palavra-passe?", a:[{t:"Num papel colado ao ecrã do computador",ok:true},{t:"Apenas na tua memória",ok:false},{t:"Num gestor de palavras-passe encriptado",ok:false}], exp:"Escrever a palavra-passe num papel visível (como colado ao ecrã) torna-a fácil de ver por qualquer pessoa que passe perto do computador." },
    { q:"Quando deves mudar imediatamente uma palavra-passe?", a:[{t:"Se suspeitares que alguém a descobriu ou a conta foi invadida",ok:true},{t:"Nunca é preciso mudar uma palavra-passe",ok:false},{t:"Só quando o site obrigar, sem outro motivo",ok:false}], exp:"Se desconfiares que uma palavra-passe foi descoberta por outra pessoa, deves mudá-la imediatamente para proteger a tua conta." },
    { q:"Além da palavra-passe, que outro método ajuda a proteger o acesso a uma conta ou dispositivo?", a:[{t:"A biometria, como a impressão digital ou o reconhecimento facial",ok:true},{t:"Escrever a palavra-passe em voz alta perto de outras pessoas",ok:false},{t:"Usar sempre a mesma palavra-passe em todo o lado",ok:false}], exp:"A biometria (impressão digital, reconhecimento facial) é outra forma de confirmar que és tu, muitas vezes usada em conjunto com a palavra-passe." },
    { q:"Uma \"frase-passe\", feita de várias palavras juntas, pode ser...", a:[{t:"Mais fácil de lembrar e, se for longa, também segura",ok:true},{t:"Sempre mais fraca do que uma palavra-passe curta",ok:false},{t:"Proibida em todos os sites",ok:false}], exp:"Uma frase-passe (por exemplo, várias palavras aleatórias juntas) pode ser mais fácil de memorizar do que uma sequência de carateres aleatórios, e ainda assim ser bastante segura se for suficientemente longa." },
    { q:"É boa prática nunca mudar uma palavra-passe importante, mesmo ao longo de vários anos?", a:[{t:"Não — vale a pena atualizar periodicamente palavras-passe de contas importantes",ok:true},{t:"Sim, uma palavra-passe deve ser usada para sempre sem qualquer alteração",ok:false},{t:"Só é preciso mudar se esqueceres a palavra-passe",ok:false}], exp:"Atualizar periodicamente as palavras-passe de contas importantes, sobretudo se houver qualquer suspeita de problema, ajuda a manter as contas mais seguras." }
  ],
  dados_pessoais: [
    { q:"Que tipo de informação nunca deves partilhar online com desconhecidos?", a:[{t:"Nome completo, morada, telefone e escola",ok:true},{t:"O teu desenho ou jogo favorito",ok:false},{t:"Uma cor que gostas",ok:false}], exp:"Dados como morada, telefone ou o nome da escola podem ser usados para te localizar ou enganar — por isso devem ficar apenas com pessoas de confiança." },
    { q:"O que deve fazer uma criança se receber uma mensagem de um desconhecido a pedir dados pessoais?", a:[{t:"Não responder e contar a um adulto de confiança",ok:true},{t:"Responder com todos os dados pedidos, para ser simpática",ok:false},{t:"Aceitar sempre, se o pedido parecer inofensivo",ok:false}], exp:"Nunca se deve partilhar dados pessoais com desconhecidos online. O mais seguro é não responder e falar imediatamente com um adulto de confiança." },
    { q:"Porque é que os dados pessoais são valiosos para quem quer enganar outras pessoas?", a:[{t:"Porque podem ser usados para roubar identidades ou enganar outras pessoas",ok:true},{t:"Não têm nenhum valor para ninguém",ok:false},{t:"Só têm valor para os pais",ok:false}], exp:"Nome, morada ou dados da família podem ser usados por burlões para se fazerem passar por outra pessoa ou para planear enganos mais elaborados." },
    { q:"É seguro partilhar a localização em tempo real com toda a gente numa rede social?", a:[{t:"Não, só deve ser partilhada com pessoas de confiança",ok:true},{t:"Sim, é sempre seguro",ok:false},{t:"Só é perigoso se fores a um sítio novo",ok:false}], exp:"Partilhar a localização publicamente pode revelar onde estás ou onde vives a desconhecidos — deve ficar reservada a pessoas de confiança." },
    { q:"O que é mais seguro fazer antes de preencher um formulário online com dados pessoais?", a:[{t:"Confirmar com um adulto se o site é de confiança e se é mesmo necessário preenchê-lo",ok:true},{t:"Preencher tudo rapidamente sem pensar",ok:false},{t:"Inventar sempre dados falsos, mesmo em sites oficiais",ok:false}], exp:"Antes de partilhar dados pessoais num formulário, vale a pena confirmar com um adulto se o site é de confiança e se essa informação é mesmo necessária." },
    { q:"O que é considerado um \"dado pessoal\"?", a:[{t:"Qualquer informação que identifique ou permita identificar uma pessoa",ok:true},{t:"Só o nome completo de alguém",ok:false},{t:"Apenas informações que estão escritas num documento oficial",ok:false}], exp:"Um dado pessoal é qualquer informação que identifique, direta ou indiretamente, uma pessoa — nome, morada, telefone, fotografias e muito mais." },
    { q:"Porque é arriscado publicar o nome da tua escola numa rede social pública?", a:[{t:"Porque pode ajudar um desconhecido a localizar-te fisicamente",ok:true},{t:"Não há qualquer risco nisso",ok:false},{t:"Só é arriscado se a escola for privada",ok:false}], exp:"Saber o nome da escola de uma criança pode ajudar alguém com más intenções a descobrir onde e quando a encontrar — por isso vale a pena ter cuidado." },
    { q:"Podes revelar a tua localização sem escrever nada sobre ti, só através de uma fotografia?", a:[{t:"Sim, pormenores visíveis na imagem (placas, uniformes, casas) podem revelar onde estás",ok:true},{t:"Não, uma fotografia nunca revela onde foi tirada",ok:false},{t:"Só se a foto tiver a localização escrita por cima",ok:false}], exp:"Mesmo sem escrever nada, uma fotografia pode mostrar pormenores — como o nome de uma rua, um uniforme escolar ou um número de porta — que revelam onde estás." },
    { q:"É correto partilhar dados pessoais de um amigo (nome, escola, morada) sem a autorização dele?", a:[{t:"Não, os dados pessoais de outras pessoas também devem ser protegidos",ok:true},{t:"Sim, desde que sejam verdadeiros",ok:false},{t:"Sim, se o amigo não se importar depois de saber",ok:false}], exp:"Proteger dados pessoais não é só sobre os teus próprios dados — também deves ter cuidado com os dados de amigos e familiares, e só os partilhar com a autorização deles." },
    { q:"Porque é arriscado divulgar o teu nome completo junto com a tua data de nascimento?", a:[{t:"Porque essa combinação pode ser usada para tentar aceder a contas ou roubar identidade",ok:true},{t:"Não há qualquer risco nessa combinação",ok:false},{t:"Só é arriscado se também disseres a tua morada",ok:false}], exp:"Nome completo e data de nascimento juntos são muitas vezes usados para confirmar identidade ou tentar recuperar o acesso a contas — por isso essa combinação deve ser protegida." },
    { q:"O que deves fazer se uma aplicação pedir mais dados pessoais do que parece necessário para funcionar?", a:[{t:"Desconfiar e pedir ajuda a um adulto antes de aceitar",ok:true},{t:"Aceitar sempre, porque as aplicações nunca pedem dados a mais",ok:false},{t:"Inventar dados falsos sem avisar ninguém",ok:false}], exp:"Se uma aplicação pedir dados que não fazem sentido para o que faz (por exemplo, um jogo pedir a tua morada), vale a pena desconfiar e pedir ajuda a um adulto." },
    { q:"O que significa \"minimizar\" a partilha de dados pessoais online?", a:[{t:"Partilhar só o que é mesmo necessário, e nada a mais",ok:true},{t:"Partilhar o máximo de dados possível, para ser mais simpático",ok:false},{t:"Nunca poder preencher nenhum formulário",ok:false}], exp:"Minimizar a partilha de dados significa dar apenas a informação estritamente necessária em cada situação, evitando partilhar dados extra sem necessidade." },
    { q:"Quem deve ter a última palavra sobre o que é feito com os teus dados pessoais, sendo tu uma criança?", a:[{t:"Tu, com o apoio e orientação dos teus pais ou encarregados de educação",ok:true},{t:"Qualquer desconhecido que peça os dados com simpatia",ok:false},{t:"As aplicações podem decidir sozinhas, sem pedir autorização",ok:false}], exp:"Os teus dados pessoais são teus — mesmo sendo criança, tens direito à privacidade, com o apoio dos teus pais ou encarregados de educação para tomar as melhores decisões." }
  ],
  instituicoes_apoio: [
    { q:"Qual é a linha de apoio gratuita em Portugal para problemas online?", a:[{t:"Linha Internet Segura: 800 21 90 90",ok:true},{t:"Linha de Saúde: 808 24 24 24",ok:false},{t:"Número da polícia local",ok:false}], exp:"A Linha Internet Segura é gratuita e apoia crianças e jovens com ciberbullying, conteúdos perturbadores ou outros problemas online." },
    { q:"O que é o CNCS?", a:[{t:"O Centro Nacional de Cibersegurança, que protege Portugal no mundo digital",ok:true},{t:"Uma marca de antivírus",ok:false},{t:"Uma rede social portuguesa",ok:false}], exp:"O Centro Nacional de Cibersegurança (CNCS) é a entidade portuguesa responsável por promover a cibersegurança e ajudar a proteger o país no mundo digital." },
    { q:"O que é o SeguraNet?", a:[{t:"Um projeto português que ensina crianças e escolas a navegar com segurança",ok:true},{t:"Um jogo de vídeo popular",ok:false},{t:"Uma empresa de telemóveis",ok:false}], exp:"O SeguraNet é um projeto nacional dedicado à literacia digital e à segurança online de crianças e jovens em contexto escolar." },
    { q:"Onde podes denunciar um problema ou conteúdo perigoso encontrado online, em Portugal?", a:[{t:"Em www.internetsegura.pt ou através da Linha Internet Segura",ok:true},{t:"Apenas na esquadra de polícia mais próxima",ok:false},{t:"Não há onde denunciar problemas online",ok:false}], exp:"O site internetsegura.pt e a Linha Internet Segura (800 21 90 90) permitem denunciar problemas online e pedir ajuda de forma gratuita e confidencial." },
    { q:"Além das instituições, quem deve ser sempre a primeira pessoa a quem contar um problema online?", a:[{t:"Um adulto de confiança, como um familiar ou professor",ok:true},{t:"Um desconhecido que se ofereceu para ajudar online",ok:false},{t:"Ninguém, é melhor resolver sozinho",ok:false}], exp:"Falar com um adulto de confiança — pais, professores ou familiares — é sempre o primeiro passo quando algo corre mal online, mesmo antes de contactar uma linha de apoio." },
    { q:"Que entidade coordena a Linha Internet Segura, em Portugal?", a:[{t:"A APAV — Associação Portuguesa de Apoio à Vítima",ok:true},{t:"Uma empresa privada de telemóveis",ok:false},{t:"Um canal de televisão",ok:false}], exp:"A Linha Internet Segura é coordenada pela APAV (Associação Portuguesa de Apoio à Vítima), no âmbito do Centro Internet Segura." },
    { q:"A Linha Internet Segura é um serviço pago ou gratuito?", a:[{t:"Gratuito e confidencial",ok:true},{t:"Pago, mas barato",ok:false},{t:"Só gratuito para adultos",ok:false}], exp:"A Linha Internet Segura (800 21 90 90) é totalmente gratuita e confidencial, disponível para crianças, jovens, pais e professores." },
    { q:"O CNCS é conhecido oficialmente como a...?", a:[{t:"Autoridade Nacional de Cibersegurança",ok:true},{t:"Autoridade Nacional de Trânsito",ok:false},{t:"Federação Portuguesa de Informática",ok:false}], exp:"O Centro Nacional de Cibersegurança (CNCS) é a Autoridade Nacional de Cibersegurança, responsável por ajudar Portugal a alcançar um elevado nível de cibersegurança." },
    { q:"Que entidade portuguesa é responsável pelo projeto SeguraNet?", a:[{t:"A Direção-Geral da Educação (DGE)",ok:true},{t:"Uma empresa de videojogos",ok:false},{t:"A Câmara Municipal de Lisboa",ok:false}], exp:"O SeguraNet é da responsabilidade da Direção-Geral da Educação (DGE), através do seu Centro de Sensibilização SeguraNet." },
    { q:"A quem se dirige principalmente o projeto SeguraNet?", a:[{t:"À comunidade educativa — alunos, professores e escolas",ok:true},{t:"Só a empresas de tecnologia",ok:false},{t:"Só a reformados",ok:false}], exp:"O SeguraNet tem como missão promover a navegação segura na comunidade educativa, com formação para professores e recursos para escolas e alunos." },
    { q:"Além do telefone, de que outra forma podes contactar a Linha Internet Segura?", a:[{t:"Por correio eletrónico ou através do site internetsegura.pt",ok:true},{t:"Só é possível ligar por telefone",ok:false},{t:"Só através de uma carta enviada pelo correio",ok:false}], exp:"Além da chamada gratuita (800 21 90 90), a Linha Internet Segura também pode ser contactada por email e através do site internetsegura.pt." },
    { q:"É só a polícia que pode ajudar com problemas relacionados com cibersegurança em Portugal?", a:[{t:"Não, há várias entidades, como o CNCS, o SeguraNet e a Linha Internet Segura",ok:true},{t:"Sim, só a polícia pode ajudar",ok:false},{t:"Não existe nenhuma entidade que ajude com estes problemas",ok:false}], exp:"Em Portugal existem várias entidades dedicadas a ajudar com problemas online, além da polícia — como o CNCS, o SeguraNet e a Linha Internet Segura." },
    { q:"Vale a pena denunciar uma situação perigosa online, mesmo que pareça pequena?", a:[{t:"Sim, ajuda a proteger-te a ti e também outras pessoas",ok:true},{t:"Não, só vale a pena denunciar problemas muito graves",ok:false},{t:"Não, denunciar nunca tem qualquer efeito",ok:false}], exp:"Denunciar situações que pareçam perigosas ou estranhas, mesmo que pareçam pequenas, ajuda as entidades a atuar e pode proteger outras pessoas do mesmo problema." }
  ],
  virus_malware: [
    { q:"O que é um vírus informático?", a:[{t:"Um programa malicioso que se espalha e pode danificar ficheiros ou roubar dados",ok:true},{t:"Uma doença que apanhamos ao usar o computador",ok:false},{t:"Um jogo que corre muito devagar",ok:false}], exp:"Um vírus informático é um programa criado para causar dano, espalhando-se entre ficheiros e computadores, muitas vezes sem que o utilizador dê conta." },
    { q:"O que é 'malware'?", a:[{t:"Um termo geral para qualquer programa malicioso, incluindo vírus",ok:true},{t:"O nome de uma marca de computadores",ok:false},{t:"Um tipo de ligação à internet",ok:false}], exp:"Malware ('software malicioso') é o termo geral que engloba vírus, spyware e outros programas criados para prejudicar dispositivos ou roubar informação." },
    { q:"Como ajuda um antivírus a proteger o computador?", a:[{t:"Deteta e bloqueia programas maliciosos antes de causarem dano",ok:true},{t:"Torna o computador mais rápido a jogar",ok:false},{t:"Impede que a bateria descarregue",ok:false}], exp:"Um antivírus atualizado analisa ficheiros e programas em busca de ameaças conhecidas, ajudando a impedir que o malware infete o dispositivo." },
    { q:"Qual destes é um comportamento arriscado que pode levar a uma infeção por malware?", a:[{t:"Instalar programas de fontes desconhecidas ou não oficiais",ok:true},{t:"Manter o sistema operativo sempre atualizado",ok:false},{t:"Usar um antivírus atualizado",ok:false}], exp:"Instalar programas fora das lojas oficiais ou de sites desconhecidos é uma das formas mais comuns de um dispositivo apanhar malware." },
    { q:"O que deve fazer uma criança se o computador começar a comportar-se de forma estranha (lento, com anúncios inesperados)?", a:[{t:"Avisar um adulto para verificarem o computador juntos",ok:true},{t:"Continuar a usar normalmente sem dizer nada",ok:false},{t:"Instalar mais programas para tentar resolver sozinha",ok:false}], exp:"Comportamentos estranhos podem ser sinal de malware — o mais seguro é avisar um adulto para que o dispositivo seja verificado." },
    { q:"Qual é geralmente considerado o primeiro programa vírico da história dos computadores?", a:[{t:"O Creeper, criado em 1971",ok:true},{t:"O Windows 95",ok:false},{t:"O primeiro telemóvel",ok:false}], exp:"O Creeper, criado em 1971 por Bob Thomas, é geralmente apontado como o primeiro programa auto-replicante da história — um precursor dos vírus informáticos modernos." },
    { q:"O Creeper, de 1971, causava grandes danos aos computadores que infetava?", a:[{t:"Não, era inofensivo — apenas mostrava uma mensagem no ecrã",ok:true},{t:"Sim, apagava todos os ficheiros",ok:false},{t:"Sim, pedia sempre dinheiro para ser removido",ok:false}], exp:"O Creeper não tinha intenções maliciosas: passava de computador para computador e limitava-se a mostrar uma mensagem — mas mostrou que um programa podia espalhar-se sozinho numa rede." },
    { q:"Como se chamava o programa criado, também em 1971, para eliminar o vírus Creeper — considerado o primeiro antivírus da história?", a:[{t:"Reaper",ok:true},{t:"Guardião",ok:false},{t:"Firewall",ok:false}], exp:"O Reaper foi criado no mesmo ano que o Creeper, para o encontrar e removê-lo — sendo por isso considerado o primeiro antivírus da história." },
    { q:"O que foi o \"Worm Morris\", de 1988?", a:[{t:"Um dos primeiros vermes informáticos a espalhar-se pela internet, infetando milhares de computadores",ok:true},{t:"O primeiro browser de internet",ok:false},{t:"Um antivírus muito popular nos anos 80",ok:false}], exp:"O Worm Morris espalhou-se pela internet em 1988 e infetou uma grande parte dos computadores ligados na altura, mostrando como um programa malicioso podia afetar muitas máquinas rapidamente." },
    { q:"O que faz um \"ransomware\"?", a:[{t:"Bloqueia ou encripta ficheiros e pede um pagamento para os libertar",ok:true},{t:"Torna o computador mais rápido",ok:false},{t:"Apenas muda as cores do ecrã",ok:false}], exp:"O ransomware é um tipo de malware que bloqueia ou torna ilegíveis os ficheiros de uma vítima, exigindo um pagamento (resgate) para os libertar — nunca se deve pagar nem tentar resolver isto sozinho, deve avisar-se sempre um adulto." },
    { q:"O que faz um \"spyware\"?", a:[{t:"Espia e recolhe informação do dispositivo sem o utilizador saber",ok:true},{t:"Protege o computador contra vírus",ok:false},{t:"Torna as fotografias mais bonitas",ok:false}], exp:"O spyware é um tipo de malware criado para espiar em segredo a atividade de um dispositivo e recolher informação sem que o utilizador dê por isso." },
    { q:"Porque se chama \"cavalo de Troia\" (trojan) a um tipo de malware?", a:[{t:"Porque se disfarça de programa útil ou inofensivo para enganar a vítima",ok:true},{t:"Porque só afeta computadores muito antigos",ok:false},{t:"Porque foi criado por um cavalo de corridas",ok:false}], exp:"Tal como no mito grego, um \"cavalo de Troia\" informático disfarça-se de algo inofensivo ou útil (um jogo, um ficheiro) para enganar a vítima e conseguir entrar no dispositivo." },
    { q:"Qual é a principal diferença entre um \"worm\" (verme) e um vírus tradicional?", a:[{t:"Um worm consegue espalhar-se sozinho entre computadores, sem precisar de um ficheiro hospedeiro",ok:true},{t:"Um worm nunca causa qualquer problema",ok:false},{t:"Não existe qualquer diferença entre os dois",ok:false}], exp:"Ao contrário de um vírus tradicional, que precisa de um ficheiro ou programa hospedeiro para se espalhar, um worm consegue replicar-se e espalhar-se sozinho através de redes." }
  ],
  jogos_seguros: [
    { q:"O que indicam as classificações etárias PEGI nos jogos?", a:[{t:"A idade mínima recomendada para jogar aquele jogo com segurança",ok:true},{t:"O preço do jogo",ok:false},{t:"O número de jogadores permitido",ok:false}], exp:"O sistema PEGI (Pan European Game Information) classifica os jogos por faixa etária, ajudando pais e crianças a escolher jogos adequados à idade." },
    { q:"O que deve fazer uma criança se um desconhecido, num jogo online, pedir para se encontrarem pessoalmente?", a:[{t:"Recusar e contar imediatamente a um adulto de confiança",ok:true},{t:"Aceitar, se a pessoa parecer simpática no jogo",ok:false},{t:"Combinar sozinha, sem dizer a ninguém",ok:false}], exp:"Nunca se deve combinar encontros com pessoas conhecidas apenas online, mesmo que pareçam simpáticas — o mais seguro é recusar e avisar um adulto." },
    { q:"É seguro partilhar dados pessoais no chat de um jogo online?", a:[{t:"Não, os chats de jogos também são espaços públicos onde há desconhecidos",ok:true},{t:"Sim, porque é só um jogo",ok:false},{t:"Só é arriscado se o jogo for muito popular",ok:false}], exp:"Os chats de jogos online são espaços onde interagem desconhecidos, por isso as mesmas regras de proteção de dados pessoais se aplicam." },
    { q:"O que deves fazer antes de fazer uma compra dentro de um jogo (como moedas ou skins)?", a:[{t:"Pedir sempre autorização a um adulto",ok:true},{t:"Comprar livremente, mesmo sem avisar ninguém",ok:false},{t:"Usar sempre o cartão de crédito dos pais sem perguntar",ok:false}], exp:"Compras dentro de jogos envolvem dinheiro real — é importante pedir sempre autorização a um adulto antes de fazer qualquer compra." },
    { q:"O que fazer se alguém for desagradável ou ameaçador no chat de um jogo?", a:[{t:"Usar o botão de denúncia/bloqueio e contar a um adulto",ok:true},{t:"Responder na mesma forma, para se defender",ok:false},{t:"Ignorar e continuar a jogar com essa pessoa normalmente",ok:false}], exp:"A maioria dos jogos tem funções para denunciar e bloquear outros jogadores — usá-las, e contar a um adulto, é a atitude mais segura." },
    { q:"O que significa a sigla PEGI, usada na classificação etária dos jogos?", a:[{t:"Pan European Game Information",ok:true},{t:"Portuguese Electronic Gaming Index",ok:false},{t:"Personal Entertainment Game Identifier",ok:false}], exp:"PEGI significa Pan European Game Information — o sistema europeu que classifica os jogos por faixa etária, ajudando a escolher jogos adequados para cada idade." },
    { q:"O que deves ter cuidado ao fazer transmissões em direto (\"streaming\") enquanto jogas?", a:[{t:"Não revelar sem querer dados pessoais, como a tua localização ou o nome da escola",ok:true},{t:"Não há nenhum cuidado especial a ter",ok:false},{t:"Só deves ter cuidado se tiveres mais de mil espectadores",ok:false}], exp:"Ao transmitires em direto, é fácil revelar sem querer informação pessoal — pelo som ao fundo, pela câmara ou até por comentários que fazes — por isso vale a pena ter atenção redobrada." },
    { q:"As regras de proteção de dados pessoais aplicam-se também ao chat de voz em jogos online, e não só ao chat de texto?", a:[{t:"Sim, aplicam-se da mesma forma, seja o chat escrito ou falado",ok:true},{t:"Não, só se aplicam ao chat de texto",ok:false},{t:"Não, no chat de voz podes dizer o que quiseres",ok:false}], exp:"Seja por texto ou por voz, os chats de jogos online continuam a ser espaços com desconhecidos — por isso as mesmas regras de proteção de dados pessoais se aplicam." }
  ],
  pegada_digital: [
    { q:"O que é a 'pegada digital'?", a:[{t:"O rasto que deixamos online através do que publicamos e partilhamos",ok:true},{t:"Uma marca física deixada por um telemóvel",ok:false},{t:"Um tipo de vírus informático",ok:false}], exp:"A pegada digital é o conjunto de informação que deixamos online — publicações, comentários, fotos — e que pode ficar acessível durante muito tempo." },
    { q:"O que acontece a uma publicação depois de ser apagada da rede social?", a:[{t:"Pode continuar a existir, por exemplo em capturas de ecrã feitas por outros",ok:true},{t:"Desaparece sempre por completo, sem deixar rasto",ok:false},{t:"Torna-se invisível só para o autor, mas mais ninguém a via antes",ok:false}], exp:"Mesmo depois de apagada, uma publicação pode já ter sido vista, guardada ou partilhada por outras pessoas — por isso é importante pensar antes de publicar." },
    { q:"Porque é importante pensar antes de publicar alguma coisa online?", a:[{t:"Porque pode ficar acessível durante muito tempo e afetar a tua imagem no futuro",ok:true},{t:"Não é importante, tudo se apaga sempre por completo",ok:false},{t:"Só é importante para adultos que trabalham",ok:false}], exp:"O que publicamos online pode ser visto por muita gente, incluindo no futuro — por isso vale sempre a pena parar e pensar antes de carregar em 'publicar'." },
    { q:"O que é mais seguro publicar sobre as tuas rotinas diárias (como o percurso para a escola)?", a:[{t:"Evitar publicar detalhes que revelem onde estás ou vais estar em cada momento",ok:true},{t:"Publicar tudo em tempo real para os amigos verem",ok:false},{t:"Só é arriscado publicar fotos, não texto",ok:false}], exp:"Publicar rotinas e localizações em tempo real pode revelar padrões sobre onde estás, o que representa um risco de segurança." },
    { q:"O que é uma boa prática antes de publicares uma foto onde aparecem outras pessoas?", a:[{t:"Pedir autorização às pessoas que aparecem na foto",ok:true},{t:"Publicar sem avisar ninguém, é só uma foto",ok:false},{t:"Marcar sempre a localização exata onde foi tirada",ok:false}], exp:"Pedir autorização antes de publicar fotos com outras pessoas respeita a privacidade delas e faz parte de uma boa pegada digital." },
    { q:"A tua pegada digital pode continuar visível daqui a vários anos, por exemplo quando procurares um emprego?", a:[{t:"Sim, pode influenciar como as outras pessoas te veem no futuro",ok:true},{t:"Não, tudo o que publicamos desaparece ao fim de um ano",ok:false},{t:"Não, a pegada digital só existe durante a infância",ok:false}], exp:"Aquilo que publicamos hoje pode continuar acessível durante muitos anos e influenciar a forma como outras pessoas — incluindo futuros empregadores — nos veem no futuro." },
    { q:"Só as fotos e publicações que fazes contam para a tua pegada digital?", a:[{t:"Não, também contam os comentários, gostos e partilhas que fazes",ok:true},{t:"Sim, só as fotos contam",ok:false},{t:"Sim, só publicações com o teu nome contam",ok:false}], exp:"A pegada digital inclui tudo o que fazes online — publicações, mas também comentários, gostos (\"likes\") e partilhas — todos deixam um rasto." },
    { q:"O que aumenta o risco ao marcares a tua localização exata numa publicação em tempo real?", a:[{t:"Revela onde estás naquele preciso momento a quem vir a publicação",ok:true},{t:"Não há qualquer risco associado a isso",ok:false},{t:"Só é arriscado se a publicação for privada",ok:false}], exp:"Marcar a localização exata em tempo real mostra imediatamente onde estás a quem tiver acesso à publicação — mesmo que sejam pessoas que não conheces bem." }
  ],
  fake_news: [
    { q:"O que são 'fake news'?", a:[{t:"Notícias falsas ou enganosas espalhadas online",ok:true},{t:"Notícias sobre acontecimentos futuros",ok:false},{t:"Notícias publicadas apenas em jornais impressos",ok:false}], exp:"Fake news são notícias falsas ou distorcidas, muitas vezes criadas para enganar ou causar confusão, e espalham-se facilmente nas redes sociais." },
    { q:"Como podes verificar se uma notícia é verdadeira?", a:[{t:"Verificar se a fonte é credível e procurar a mesma notícia noutros meios",ok:true},{t:"Acreditar sempre se tiver muitos gostos ou partilhas",ok:false},{t:"Acreditar sempre se o título for muito chocante",ok:false}], exp:"Confirmar a fonte, procurar a notícia noutros meios credíveis e desconfiar de títulos muito sensacionalistas ajuda a identificar informação falsa." },
    { q:"Um título muito chocante ou exagerado é sinal de quê?", a:[{t:"Pode ser um sinal de alerta de que a notícia é falsa ou enganosa",ok:true},{t:"É sempre sinal de que a notícia é verdadeira",ok:false},{t:"Não tem qualquer significado",ok:false}], exp:"Muitas fake news usam títulos exagerados ou chocantes para atrair atenção e cliques rapidamente, mesmo sem conteúdo verdadeiro por trás." },
    { q:"Porque se espalham tão depressa as fake news nas redes sociais?", a:[{t:"Porque são fáceis de partilhar e muitas vezes despertam emoções fortes",ok:true},{t:"Porque as redes sociais verificam sempre tudo antes de ser publicado",ok:false},{t:"Não se espalham mais depressa do que notícias verdadeiras",ok:false}], exp:"As fake news são pensadas para despertar emoções fortes (medo, indignação), o que faz com que sejam partilhadas rapidamente antes de serem verificadas." },
    { q:"O que deves fazer antes de partilhares uma notícia com os teus amigos ou família?", a:[{t:"Confirmar se é verdadeira, mesmo que pareça interessante",ok:true},{t:"Partilhar sempre imediatamente, sem verificar",ok:false},{t:"Só é preciso verificar notícias sobre desporto",ok:false}], exp:"Partilhar informação falsa, mesmo sem intenção, contribui para a espalhar — por isso vale a pena confirmar antes de partilhar." },
    { q:"O que são \"deepfakes\"?", a:[{t:"Vídeos ou imagens falsos, criados com inteligência artificial, que parecem reais",ok:true},{t:"Um tipo de jogo de vídeo popular",ok:false},{t:"Notícias sobre acontecimentos que já foram confirmados como verdadeiros",ok:false}], exp:"Deepfakes são vídeos, imagens ou áudios falsos, criados com recurso a inteligência artificial, que podem parecer extremamente reais — por isso é cada vez mais importante confirmar as fontes antes de acreditar no que se vê." },
    { q:"As fake news aparecem apenas em forma de texto?", a:[{t:"Não, também podem ser imagens, vídeos ou áudios manipulados",ok:true},{t:"Sim, só existem fake news escritas",ok:false},{t:"Não, só existem em forma de imagem",ok:false}], exp:"As fake news podem assumir várias formas — texto, imagens, vídeos e até áudios manipulados — por isso é importante verificar qualquer tipo de conteúdo antes de acreditar ou partilhar." },
    { q:"Existem sites e organizações dedicadas a verificar se uma notícia é verdadeira ou falsa?", a:[{t:"Sim, chamam-se serviços de verificação de factos (fact-checking)",ok:true},{t:"Não, ninguém verifica notícias online",ok:false},{t:"Só existem para notícias sobre desporto",ok:false}], exp:"Existem organizações especializadas em verificação de factos (fact-checking) que analisam notícias e conteúdos para confirmar se são verdadeiros, ajudando a combater a desinformação." }
  ],
  phishing: [
    { q:"O que é o phishing?", a:[{t:"Uma tentativa de enganar alguém, fingindo ser de confiança, para roubar dados",ok:true},{t:"Um jogo de pesca online muito popular",ok:false},{t:"Um vírus que apaga ficheiros do computador",ok:false}], exp:"Phishing é quando alguém finge ser uma entidade de confiança (banco, escola, amigo) para enganar a vítima e roubar palavras-passe ou dados pessoais." },
    { q:"Qual é um sinal comum de uma mensagem de phishing?", a:[{t:"Um link suspeito com um pedido urgente para agir imediatamente",ok:true},{t:"Um email do teu professor a marcar um trabalho de casa",ok:false},{t:"Uma mensagem sem qualquer link ou pedido",ok:false}], exp:"Mensagens de phishing costumam criar urgência ('a tua conta vai ser bloqueada!') e incluir links suspeitos para levar a vítima a clicar sem pensar." },
    { q:"O que deves fazer se receberes uma mensagem suspeita a pedir para clicares num link e inserires uma palavra-passe?", a:[{t:"Não clicar e avisar um adulto de confiança",ok:true},{t:"Clicar e inserir a palavra-passe rapidamente",ok:false},{t:"Reenviar a mensagem a todos os amigos para avisar",ok:false}], exp:"Nunca se deve clicar em links suspeitos nem inserir dados. O mais seguro é ignorar a mensagem e avisar um adulto de confiança." },
    { q:"As mensagens de phishing só chegam por email?", a:[{t:"Não, também podem chegar por SMS, redes sociais ou aplicações de mensagens",ok:true},{t:"Sim, só existem por email",ok:false},{t:"Só existem em chamadas telefónicas",ok:false}], exp:"O phishing pode chegar por email, SMS, redes sociais ou até chamadas — o importante é reconhecer os sinais, seja qual for o meio." },
    { q:"Porque é que os atacantes usam nomes de empresas ou pessoas conhecidas no phishing?", a:[{t:"Para parecerem de confiança e enganar mais facilmente a vítima",ok:true},{t:"Porque é obrigatório por lei identificarem-se corretamente",ok:false},{t:"Não usam nomes conhecidos, usam sempre nomes aleatórios",ok:false}], exp:"Ao fingir ser um banco, uma escola ou um amigo, o atacante tenta ganhar a confiança da vítima mais depressa, para que esta baixe a guarda." },
    { q:"Podem existir tentativas de phishing feitas através de chamadas telefónicas, e não só por email ou SMS?", a:[{t:"Sim, este tipo de phishing por telefone é por vezes chamado de \"vishing\"",ok:true},{t:"Não, o phishing só existe por email",ok:false},{t:"Não, chamadas telefónicas são sempre seguras",ok:false}], exp:"O phishing pode acontecer por telefone (chamado de \"vishing\"), além de email, SMS ou redes sociais — em qualquer meio, o objetivo é sempre enganar a vítima para obter dados ou dinheiro." },
    { q:"O que deves fazer se receberes uma mensagem a fingir ser de um amigo ou familiar, pedindo dinheiro com urgência?", a:[{t:"Confirmar diretamente com essa pessoa, por outro meio, antes de fazer o que é pedido",ok:true},{t:"Enviar o dinheiro imediatamente, porque parece urgente",ok:false},{t:"Ignorar sempre sem confirmar nada",ok:false}], exp:"Contas de amigos ou familiares podem ser roubadas por atacantes que depois pedem dinheiro com urgência — o mais seguro é confirmar diretamente com a pessoa, por outro meio, antes de agir." },
    { q:"Um endereço de site com pequenos erros ortográficos (por exemplo, \"bancoo.pt\" em vez de \"banco.pt\") pode ser sinal de quê?", a:[{t:"Pode ser um site falso criado para enganar a vítima",ok:true},{t:"Não tem qualquer significado, é só um erro sem importância",ok:false},{t:"É sempre sinal de que o site é mais seguro",ok:false}], exp:"Pequenas alterações num endereço de site (letras a mais, trocadas ou diferentes) são um sinal clássico de um site falso criado para se parecer com o original e enganar quem o visita." }
  ],
  dispositivos: [
    { q:"Porque é importante manter os dispositivos sempre atualizados?", a:[{t:"Porque as atualizações corrigem falhas de segurança conhecidas",ok:true},{t:"As atualizações servem só para mudar o design dos ícones",ok:false},{t:"Não é importante, podes ignorar sempre as atualizações",ok:false}], exp:"As atualizações de software corrigem falhas de segurança que os atacantes podiam explorar — adiá-las deixa o dispositivo mais vulnerável." },
    { q:"É seguro fazer login numa conta importante através de uma rede Wi-Fi pública?", a:[{t:"Não é recomendado, porque redes públicas costumam ser menos seguras",ok:true},{t:"Sim, é sempre igualmente seguro",ok:false},{t:"Só é arriscado se a rede tiver palavra-passe",ok:false}], exp:"Redes Wi-Fi públicas podem não ser seguras, e dados enviados nelas podem, em certos casos, ser intercetados — por isso deve evitar-se aceder a contas sensíveis nesses locais." },
    { q:"O que ajuda a proteger um telemóvel ou tablet em caso de perda ou roubo?", a:[{t:"Ter um código de bloqueio ou reconhecimento biométrico ativado",ok:true},{t:"Deixar o ecrã sempre desbloqueado, para ser mais rápido de usar",ok:false},{t:"Escrever o código de desbloqueio na capa do telemóvel",ok:false}], exp:"Um código de bloqueio, impressão digital ou reconhecimento facial impede que outra pessoa aceda facilmente aos teus dados se o dispositivo for perdido ou roubado." },
    { q:"O que deves fazer antes de instalar uma nova aplicação no telemóvel?", a:[{t:"Verificar se vem de uma loja oficial e pedir ajuda a um adulto se tiveres dúvidas",ok:true},{t:"Instalar imediatamente qualquer aplicação recomendada por um desconhecido",ok:false},{t:"Não é preciso verificar nada antes de instalar",ok:false}], exp:"Instalar aplicações apenas de lojas oficiais (como App Store ou Google Play), e com apoio de um adulto quando necessário, reduz o risco de instalar programas maliciosos." },
    { q:"Porque é boa ideia desligar o Bluetooth e o Wi-Fi quando não estão a ser usados?", a:[{t:"Reduz a exposição do dispositivo a ligações não autorizadas",ok:true},{t:"Não tem qualquer efeito na segurança do dispositivo",ok:false},{t:"Só serve para poupar espaço de armazenamento",ok:false}], exp:"Manter ligações sem fios ativas sem necessidade aumenta a superfície de exposição do dispositivo a tentativas de ligação indesejadas." },
    { q:"O que é uma \"firewall\" (proteção de rede)?", a:[{t:"Uma barreira de segurança que controla e filtra o tráfego entre um dispositivo e a internet",ok:true},{t:"Um tipo de vírus que danifica o computador",ok:false},{t:"Um programa que serve só para desenhar",ok:false}], exp:"Uma firewall é uma barreira de segurança, feita de software ou hardware, que controla e filtra as ligações entre um dispositivo e a internet, ajudando a bloquear acessos não autorizados." },
    { q:"Deves conceder a uma aplicação todas as permissões que ela pedir (câmara, microfone, localização), mesmo sem saber porquê?", a:[{t:"Não, só devem ser dadas as permissões que fazem sentido para o que a aplicação faz",ok:true},{t:"Sim, todas as aplicações precisam de todas as permissões",ok:false},{t:"Sim, recusar permissões estraga sempre o dispositivo",ok:false}], exp:"As permissões (câmara, microfone, localização) devem ser dadas com cuidado — só faz sentido conceder as que a aplicação realmente precisa para funcionar." },
    { q:"Porque é boa prática desativar ligações automáticas a redes desconhecidas nos teus dispositivos?", a:[{t:"Reduz o risco de ligações indesejadas e mantém mais controlo sobre o dispositivo",ok:true},{t:"Não faz qualquer diferença na segurança",ok:false},{t:"Só serve para poupar espaço de armazenamento",ok:false}], exp:"Desativar ligações automáticas a redes desconhecidas reduz o risco de o dispositivo se ligar sozinho a redes pouco seguras sem que dês por isso." }
  ],
  regras_familia: [
    { q:"Porque é útil combinar regras de tempo de ecrã com a família?", a:[{t:"Ajuda a criar um equilíbrio saudável entre o mundo digital e outras atividades",ok:true},{t:"Não serve para nada, é só para chatear as crianças",ok:false},{t:"Serve só para os pais controlarem tudo sem explicar porquê",ok:false}], exp:"Combinar regras claras sobre tempo de ecrã ajuda a equilibrar o tempo online com outras atividades importantes, como brincar, estudar e dormir bem." },
    { q:"O que deve fazer uma criança se algo a incomodar ou assustar durante o uso da internet?", a:[{t:"Contar imediatamente a um adulto de confiança, sem medo de ser repreendida",ok:true},{t:"Esconder o que aconteceu para não ter o telemóvel retirado",ok:false},{t:"Resolver sempre sozinha, sem pedir ajuda",ok:false}], exp:"Falar abertamente com a família sobre o que corre mal online, sem medo de castigo, é essencial para que os adultos possam ajudar a tempo." },
    { q:"Qual é a vantagem de os pais ou encarregados de educação conhecerem as aplicações que a criança usa?", a:[{t:"Podem ajudar a perceber os riscos e definir regras adequadas para cada aplicação",ok:true},{t:"Não tem nenhuma vantagem, cada um deve usar o que quiser sem falar",ok:false},{t:"Serve só para os pais espiarem tudo sem a criança saber",ok:false}], exp:"Quando os adultos conhecem as aplicações usadas, conseguem ajudar a identificar riscos específicos e a definir regras mais adequadas em conjunto com a criança." },
    { q:"O que são aplicações de controlo parental?", a:[{t:"Ferramentas que ajudam os pais a gerir tempo de ecrã e a filtrar conteúdos",ok:true},{t:"Jogos criados especialmente para pais",ok:false},{t:"Um tipo de antivírus só para adultos",ok:false}], exp:"As aplicações de controlo parental ajudam as famílias a gerir tempo de ecrã, filtrar conteúdos inadequados e acompanhar o uso da internet de forma equilibrada." },
    { q:"Porque é importante conversar em família sobre o que se vê online?", a:[{t:"Ajuda a criança a interpretar melhor o que encontra e a sentir-se apoiada",ok:true},{t:"Não é importante, cada um deve navegar sozinho sem falar sobre isso",ok:false},{t:"Só é importante se a criança tiver algum problema grave",ok:false}], exp:"Conversar regularmente em família sobre experiências online ajuda a criança a desenvolver espírito crítico e a sentir-se à vontade para pedir ajuda quando precisar." },
    { q:"Além de tempo de ecrã, que outro tipo de regra pode ser combinada em família sobre o uso da tecnologia?", a:[{t:"Que tipo de conteúdos ou aplicações são adequados para a idade da criança",ok:true},{t:"Só existem regras sobre o tempo de ecrã",ok:false},{t:"Não faz sentido combinar mais nenhuma regra em família",ok:false}], exp:"Além do tempo de ecrã, as famílias podem combinar regras sobre que tipo de conteúdos e aplicações são adequados, e o que fazer se algo correr mal online." },
    { q:"É boa ideia ter conversas regulares em família sobre o que se faz online, e não só quando há um problema?", a:[{t:"Sim, ajuda a criar confiança e hábitos digitais saudáveis ao longo do tempo",ok:true},{t:"Não, só se deve falar sobre isso quando há um problema grave",ok:false},{t:"Não, cada pessoa deve gerir sozinha o seu uso da tecnologia",ok:false}], exp:"Conversar regularmente em família sobre experiências online, e não só quando surge um problema, ajuda a criar confiança e a desenvolver hábitos digitais saudáveis." },
    { q:"As regras de ecrã combinadas em família devem ser sempre exatamente iguais para todas as idades?", a:[{t:"Não, faz sentido adaptá-las à idade e às necessidades de cada criança",ok:true},{t:"Sim, devem ser sempre exatamente iguais para todos",ok:false},{t:"Não existe relação entre a idade e as regras de ecrã",ok:false}], exp:"As regras de tempo de ecrã e uso da tecnologia podem (e devem) adaptar-se à idade e às necessidades específicas de cada criança na família." }
  ],
  wifi_publico: [
    { q:"Porque é que uma rede Wi-Fi pública pode ser menos segura do que a de casa?", a:[{t:"Porque é partilhada por muitas pessoas desconhecidas e pode não estar bem protegida",ok:true},{t:"É sempre exatamente tão segura quanto a rede de casa",ok:false},{t:"As redes públicas são sempre mais seguras que as privadas",ok:false}], exp:"Redes Wi-Fi públicas são usadas por muitas pessoas desconhecidas e por vezes têm proteções mais fracas, o que aumenta o risco de os dados serem intercetados." },
    { q:"O que deves evitar fazer quando estás ligado a um Wi-Fi público?", a:[{t:"Fazer login em contas com dados sensíveis, como o banco",ok:true},{t:"Consultar uma página informativa sem fazer login",ok:false},{t:"Ver a hora ou o tempo previsto",ok:false}], exp:"Aceder a contas sensíveis (como contas bancárias) em Wi-Fi público aumenta o risco de os dados serem intercetados — é mais seguro esperar por uma rede de confiança." },
    { q:"O que deves verificar antes de ligar o teu dispositivo a uma rede Wi-Fi pública?", a:[{t:"Se é mesmo a rede oficial do local, e não uma rede falsa com nome parecido",ok:true},{t:"Não é preciso verificar nada, todas as redes públicas são idênticas",ok:false},{t:"Só é preciso verificar a velocidade da ligação",ok:false}], exp:"Existem redes falsas criadas por atacantes com nomes parecidos aos oficiais — confirmar o nome exato da rede com o estabelecimento ajuda a evitar armadilhas." },
    { q:"É boa ideia desativar a ligação automática a redes Wi-Fi desconhecidas no telemóvel?", a:[{t:"Sim, evita que o dispositivo se ligue sozinho a redes pouco seguras",ok:true},{t:"Não, é sempre melhor estar ligado ao máximo de redes possível",ok:false},{t:"Não faz qualquer diferença de segurança",ok:false}], exp:"Desativar a ligação automática impede que o telemóvel se ligue sozinho a redes desconhecidas e potencialmente inseguras sem que dês por isso." },
    { q:"O que pode ajudar a proteger os teus dados quando precisas de usar Wi-Fi público?", a:[{t:"Evitar transmitir dados sensíveis e confirmar com um adulto as melhores práticas",ok:true},{t:"Partilhar a palavra-passe da rede com toda a gente à volta",ok:false},{t:"Desligar o antivírus para a ligação ser mais rápida",ok:false}], exp:"Evitar atividades sensíveis em redes públicas e pedir orientação a um adulto sobre boas práticas ajuda a manter os teus dados protegidos." },
    { q:"O que é uma VPN e como pode ajudar em redes Wi-Fi públicas?", a:[{t:"Uma ferramenta que ajuda a encriptar e proteger a ligação à internet",ok:true},{t:"Um tipo de vírus que ataca redes Wi-Fi",ok:false},{t:"Um jogo online muito popular",ok:false}], exp:"Uma VPN (rede privada virtual) é uma ferramenta que ajuda a encriptar a ligação à internet, tornando mais difícil que os dados sejam intercetados em redes menos seguras, como o Wi-Fi público." },
    { q:"Depois de usares uma rede Wi-Fi pública, é boa ideia remover essa rede do teu dispositivo?", a:[{t:"Sim, evita que o dispositivo se volte a ligar automaticamente a ela no futuro",ok:true},{t:"Não, o dispositivo deve manter sempre todas as redes guardadas",ok:false},{t:"Não faz qualquer diferença",ok:false}], exp:"Remover redes Wi-Fi públicas depois de as usares evita que o teu dispositivo se ligue automaticamente a elas mais tarde, sem que tenhas essa intenção." },
    { q:"É seguro fazer compras online, com dados de cartão, através de uma rede Wi-Fi pública?", a:[{t:"Não é recomendado, é preferível esperar por uma rede de confiança",ok:true},{t:"Sim, é sempre igualmente seguro",ok:false},{t:"Só é arriscado se a compra for muito cara",ok:false}], exp:"Introduzir dados de pagamento numa rede Wi-Fi pública aumenta o risco de esses dados serem intercetados — o mais seguro é esperar por uma rede de confiança." }
  ],
  copias_seguranca: [
    { q:"O que é uma cópia de segurança (backup)?", a:[{t:"Uma cópia extra dos teus ficheiros guardada noutro local, para os recuperares se algo correr mal",ok:true},{t:"Um tipo de vírus informático",ok:false},{t:"Uma segunda palavra-passe para a mesma conta",ok:false}], exp:"Uma cópia de segurança é uma cópia extra dos teus ficheiros importantes, guardada numa pen, disco externo ou na nuvem, para os recuperares em caso de perda." },
    { q:"Em que situações uma cópia de segurança pode salvar o teu trabalho?", a:[{t:"Se o computador avariar, apanhar um vírus ou o ficheiro for apagado por acidente",ok:true},{t:"Só é útil se perderes o telemóvel",ok:false},{t:"Nunca é realmente útil na prática",ok:false}], exp:"Avarias, vírus ou apagar um ficheiro sem querer são situações comuns em que uma cópia de segurança permite recuperar o trabalho perdido." },
    { q:"Onde podes guardar cópias de segurança dos teus trabalhos escolares?", a:[{t:"Numa pen USB ou num serviço de armazenamento na nuvem",ok:true},{t:"Só faz sentido guardá-los no mesmo computador, sem cópia",ok:false},{t:"Não é possível guardar cópias de trabalhos digitais",ok:false}], exp:"Guardar cópias numa pen USB ou na nuvem (como Google Drive ou OneDrive) garante que os ficheiros ficam protegidos mesmo que o computador tenha um problema." },
    { q:"Com que regularidade é boa ideia fazer cópias de segurança de trabalhos importantes?", a:[{t:"Regularmente, sempre que fazes alterações importantes",ok:true},{t:"Só uma vez, no fim de todos os trabalhos do ano",ok:false},{t:"Nunca é preciso, os ficheiros nunca se perdem",ok:false}], exp:"Fazer cópias de segurança regularmente, à medida que o trabalho avança, evita perder muito progresso caso algo corra mal." },
    { q:"Além de proteger trabalhos escolares, o que mais vale a pena guardar em cópia de segurança?", a:[{t:"Fotografias e ficheiros pessoais importantes",ok:true},{t:"Não vale a pena guardar mais nada além de trabalhos escolares",ok:false},{t:"Apenas jogos instalados no computador",ok:false}], exp:"Fotografias e outros ficheiros pessoais também podem perder-se com avarias ou vírus — por isso também vale a pena incluí-los nas cópias de segurança." },
    { q:"O que significa a chamada \"regra 3-2-1\" das cópias de segurança?", a:[{t:"Ter 3 cópias dos dados, em 2 tipos de suporte diferentes, com 1 delas fora de casa",ok:true},{t:"Fazer cópias de segurança só 3 vezes por ano",ok:false},{t:"Ter sempre exatamente 3 palavras-passe diferentes",ok:false}], exp:"A regra 3-2-1 é uma boa prática de cópias de segurança: manter 3 cópias dos dados importantes, em 2 tipos de suporte diferentes (por exemplo, disco e nuvem), com pelo menos 1 delas guardada fora de casa." },
    { q:"As cópias de segurança na nuvem substituem completamente a necessidade de guardar ficheiros no próprio dispositivo?", a:[{t:"Não necessariamente — muitas pessoas usam as duas formas em conjunto, para maior segurança",ok:true},{t:"Sim, nunca é preciso guardar nada localmente",ok:false},{t:"Não, a nuvem nunca deve ser usada",ok:false}], exp:"Guardar cópias tanto localmente como na nuvem (armazenamento online) é uma boa prática, pois combina a rapidez de acesso local com a segurança extra de ter uma cópia noutro sítio." },
    { q:"Uma cópia de segurança pode ajudar mesmo depois de um ataque de ransomware que encripta os teus ficheiros?", a:[{t:"Sim, se a cópia for guardada separadamente e não estiver ligada ao dispositivo infetado",ok:true},{t:"Não, as cópias de segurança nunca ajudam contra ransomware",ok:false},{t:"Só ajuda se o ransomware for muito antigo",ok:false}], exp:"Ter uma cópia de segurança guardada separadamente (por exemplo, desligada do computador ou numa conta diferente) permite recuperar os ficheiros mesmo que o dispositivo original seja atacado por ransomware." }
  ],
  acessibilidade_digital: [
    { q:"O que é a acessibilidade digital?", a:[{t:"Tornar a tecnologia utilizável por todas as pessoas, incluindo as que têm deficiência",ok:true},{t:"Um tipo de ligação à internet mais rápida",ok:false},{t:"Um programa que só existe em computadores caros",ok:false}], exp:"A acessibilidade digital garante que sites, aplicações e dispositivos podem ser usados por todas as pessoas, independentemente de terem alguma deficiência." },
    { q:"O que faz um leitor de ecrã?", a:[{t:"Lê em voz alta o conteúdo do ecrã, ajudando pessoas com dificuldades visuais",ok:true},{t:"Torna o ecrã mais brilhante",ok:false},{t:"Apaga automaticamente notificações",ok:false}], exp:"Um leitor de ecrã converte texto em voz, permitindo que pessoas com dificuldades visuais acedam ao conteúdo de sites e aplicações." },
    { q:"Como podem as legendas automáticas ajudar na acessibilidade digital?", a:[{t:"Permitem que pessoas com dificuldades auditivas acompanhem vídeos e conteúdos",ok:true},{t:"Servem apenas para traduzir para outras línguas",ok:false},{t:"Não têm qualquer relação com acessibilidade",ok:false}], exp:"As legendas automáticas ajudam pessoas com dificuldades auditivas, e também quem está num ambiente onde não pode ouvir o som, a acompanhar o conteúdo." },
    { q:"Porque são importantes os comandos por voz em dispositivos digitais?", a:[{t:"Permitem que pessoas com dificuldades motoras usem o dispositivo mais facilmente",ok:true},{t:"Servem apenas para tornar os jogos mais divertidos",ok:false},{t:"Não têm nenhuma utilidade prática",ok:false}], exp:"Os comandos por voz permitem controlar dispositivos sem usar as mãos, o que é especialmente útil para pessoas com dificuldades motoras." },
    { q:"Qual é o objetivo geral da acessibilidade digital?", a:[{t:"Garantir que ninguém fica de fora do mundo digital por causa de uma dificuldade ou deficiência",ok:true},{t:"Tornar a tecnologia mais cara e exclusiva",ok:false},{t:"Limitar o acesso à internet a certas pessoas",ok:false}], exp:"O objetivo da acessibilidade digital é incluir todas as pessoas, garantindo que a tecnologia é útil e utilizável independentemente das suas capacidades." },
    { q:"O que é o \"texto alternativo\" (alt text) numa imagem publicada online?", a:[{t:"Uma descrição em texto da imagem, lida por leitores de ecrã para pessoas com dificuldades visuais",ok:true},{t:"Um título decorativo sem qualquer função",ok:false},{t:"Um tipo de filtro para tornar a imagem mais colorida",ok:false}], exp:"O texto alternativo é uma descrição escrita de uma imagem que os leitores de ecrã podem ler em voz alta, ajudando pessoas com dificuldades visuais a perceberem o que a imagem mostra." },
    { q:"O alto contraste de cores e o texto grande em algumas aplicações servem para ajudar quem?", a:[{t:"Pessoas com dificuldades de visão a ler o conteúdo com mais facilidade",ok:true},{t:"Servem apenas para embelezar a aplicação",ok:false},{t:"Não têm qualquer relação com acessibilidade",ok:false}], exp:"Opções como alto contraste e texto ampliado ajudam pessoas com dificuldades de visão a usar aplicações e sites com mais facilidade e conforto." },
    { q:"A acessibilidade digital só beneficia pessoas com deficiência permanente?", a:[{t:"Não, também pode ajudar em situações temporárias, como um braço partido ou ambiente ruidoso",ok:true},{t:"Sim, só serve para pessoas com deficiência permanente",ok:false},{t:"Não beneficia ninguém na prática",ok:false}], exp:"A acessibilidade digital ajuda também em situações temporárias — por exemplo, legendas úteis num ambiente ruidoso, ou comandos por voz com um braço partido — beneficiando muito mais pessoas do que se poderia pensar." }
  ],
  spam_compras: [
    { q:"O que é 'spam'?", a:[{t:"Mensagens indesejadas, muitas vezes publicidade enganosa, enviadas em grande quantidade",ok:true},{t:"Um tipo de vírus que apaga o disco rígido",ok:false},{t:"Um jogo online muito popular",ok:false}], exp:"Spam são mensagens não solicitadas, geralmente publicidade ou ofertas, enviadas em massa por email, SMS ou redes sociais." },
    { q:"O que deves suspeitar de uma oferta online 'boa demais para ser verdade'?", a:[{t:"Provavelmente é uma burla ou publicidade enganosa",ok:true},{t:"É sempre uma oferta genuína e vantajosa",ok:false},{t:"Não há nada a suspeitar em ofertas muito boas",ok:false}], exp:"Ofertas exageradamente vantajosas são um sinal clássico de burla — vale sempre a pena desconfiar e confirmar antes de agir." },
    { q:"O que deves confirmar antes de fazer uma compra num site desconhecido?", a:[{t:"Se o site é oficial e de confiança, pedindo ajuda a um adulto se tiveres dúvidas",ok:true},{t:"Não é preciso confirmar nada, todos os sites são seguros",ok:false},{t:"Basta o site ter cores bonitas para ser de confiança",ok:false}], exp:"Confirmar a autenticidade de um site, com apoio de um adulto quando necessário, ajuda a evitar burlas e sites falsos criados para roubar dinheiro ou dados." },
    { q:"Deve uma criança partilhar dados do cartão de crédito dos pais numa página suspeita?", a:[{t:"Não, nunca sem autorização e supervisão de um adulto",ok:true},{t:"Sim, se a página parecer profissional",ok:false},{t:"Sim, desde que seja rápido",ok:false}], exp:"Dados de pagamento nunca devem ser partilhados sem autorização e acompanhamento de um adulto, especialmente em páginas de confiança duvidosa." },
    { q:"O que fazer com emails ou mensagens de spam que recebes?", a:[{t:"Não clicar em nenhum link e apagar ou marcar como spam",ok:true},{t:"Reencaminhar sempre a todos os contactos",ok:false},{t:"Responder para pedir mais informações",ok:false}], exp:"O mais seguro com mensagens de spam é não clicar em nada, apagá-las ou usar a opção de marcar como spam disponível na maioria dos serviços de email." },
    { q:"O que é um sinal básico de que um site de compras usa uma ligação mais segura?", a:[{t:"Uma ligação encriptada, normalmente indicada por um cadeado junto ao endereço no navegador",ok:true},{t:"Um site com muitas cores vivas",ok:false},{t:"Um site sem qualquer tipo de anúncio",ok:false}], exp:"Um sinal básico de segurança num site de compras é a ligação encriptada (HTTPS), normalmente indicada por um ícone de cadeado junto ao endereço no navegador — mas, mesmo assim, vale sempre a pena confirmar se o site é de confiança." },
    { q:"Os filtros de spam nos serviços de email servem para quê?", a:[{t:"Identificar e separar automaticamente mensagens indesejadas das restantes",ok:true},{t:"Apagar todos os emails automaticamente",ok:false},{t:"Impedir o envio de qualquer email",ok:false}], exp:"Os filtros de spam analisam as mensagens recebidas e tentam identificar as que são indesejadas ou suspeitas, separando-as automaticamente da caixa de entrada principal." },
    { q:"É seguro clicar num anúncio muito chamativo que promete um prémio grátis só por clicares?", a:[{t:"Não, este tipo de anúncio é muitas vezes uma burla ou publicidade enganosa",ok:true},{t:"Sim, prémios grátis são sempre genuínos",ok:false},{t:"Sim, desde que o anúncio tenha muitas cores",ok:false}], exp:"Anúncios que prometem prémios fáceis e imediatos só por clicar são um clássico sinal de alerta de burla ou publicidade enganosa — o mais seguro é não clicar." }
  ],
  denuncia_conteudo: [
    { q:"Para que serve o botão de denúncia nas redes sociais e plataformas online?", a:[{t:"Para reportar conteúdos ou comportamentos impróprios às plataformas",ok:true},{t:"Para apagar a própria conta imediatamente",ok:false},{t:"Para mudar a cor do perfil",ok:false}], exp:"O botão de denúncia permite reportar conteúdos ofensivos, perigosos ou impróprios, para que a plataforma possa analisar e agir." },
    { q:"O que deves fazer se veres um conteúdo que te faz sentir desconfortável ou assustado online?", a:[{t:"Denunciar o conteúdo e contar a um adulto de confiança",ok:true},{t:"Partilhar com todos os amigos para verem também",ok:false},{t:"Ignorar completamente e não dizer a ninguém",ok:false}], exp:"Denunciar o conteúdo através da plataforma e falar com um adulto de confiança são os passos certos para lidar com conteúdo perturbador online." },
    { q:"É um direito ou um capricho pedir ajuda quando algo corre mal online?", a:[{t:"É um direito de qualquer pessoa, e não há vergonha em pedir ajuda",ok:true},{t:"É um sinal de fraqueza que deve ser evitado",ok:false},{t:"Só as crianças pequenas podem pedir ajuda",ok:false}], exp:"Pedir ajuda quando algo corre mal online é um direito de qualquer utilizador da internet, seja qual for a sua idade." },
    { q:"Além de denunciar, o que mais podes fazer perante um utilizador que te incomoda online?", a:[{t:"Bloqueá-lo, para deixar de receber mensagens ou ver conteúdos dele",ok:true},{t:"Nada mais pode ser feito além de denunciar",ok:false},{t:"Responder de forma agressiva para o afastar",ok:false}], exp:"Além de denunciar, bloquear um utilizador impede que ele continue a contactar-te ou a aparecer no teu feed, aumentando a tua segurança." },
    { q:"Denunciar um conteúdo prejudicial ajuda só a própria pessoa ou também outras?", a:[{t:"Ajuda também outras pessoas, ao alertar a plataforma para remover o conteúdo",ok:true},{t:"Só beneficia a pessoa que denunciou",ok:false},{t:"Não tem qualquer efeito na plataforma",ok:false}], exp:"Ao denunciar, ajudas a plataforma a identificar e remover conteúdos prejudiciais, o que protege também outras pessoas que os pudessem ver." },
    { q:"Depois de denunciares um conteúdo numa plataforma, o que costuma acontecer a seguir?", a:[{t:"A plataforma analisa a denúncia e decide se remove o conteúdo ou toma outra medida",ok:true},{t:"Nada acontece nunca depois de uma denúncia",ok:false},{t:"O conteúdo é sempre removido de imediato, sem qualquer análise",ok:false}], exp:"Depois de uma denúncia, a plataforma normalmente analisa o conteúdo reportado antes de decidir se o remove, avisa o utilizador responsável ou toma outra medida." },
    { q:"Além de denunciar dentro da própria plataforma, há outras formas de reportar conteúdo perigoso online, em Portugal?", a:[{t:"Sim, por exemplo através da Linha Internet Segura ou do site internetsegura.pt",ok:true},{t:"Não, só é possível denunciar dentro de cada aplicação",ok:false},{t:"Não existe nenhuma outra forma de denunciar",ok:false}], exp:"Além das ferramentas de denúncia de cada plataforma, em Portugal também é possível reportar conteúdo perigoso ou ilegal através da Linha Internet Segura e do site internetsegura.pt." },
    { q:"Denunciar um conteúdo é o mesmo que bloquear a pessoa que o publicou?", a:[{t:"Não, são ações diferentes que podem ser usadas em conjunto",ok:true},{t:"Sim, é exatamente a mesma coisa",ok:false},{t:"Não, bloquear é sempre mais grave do que denunciar",ok:false}], exp:"Denunciar reporta o conteúdo à plataforma para análise, enquanto bloquear impede que essa pessoa continue a contactar-te — são ações diferentes e podem ser usadas em conjunto." }
  ],
  identidade_digital: [
    { q:"Qual é a idade mínima habitual para criar conta nas principais redes sociais?", a:[{t:"13 anos, na maioria das plataformas (Instagram, TikTok, YouTube)",ok:true},{t:"10 anos, com autorização dos pais",ok:false},{t:"18 anos em todas as plataformas",ok:false}], exp:"A maioria das grandes plataformas exige, no mínimo, 13 anos para criar conta, seguindo regras internacionais de proteção de menores." },
    { q:"O que significa ter um 'perfil privado' numa rede social?", a:[{t:"Que só as pessoas aprovadas pelo utilizador podem ver as suas publicações",ok:true},{t:"Que ninguém, nem o próprio utilizador, pode ver as publicações",ok:false},{t:"Que o perfil é automaticamente apagado ao fim de um dia",ok:false}], exp:"Um perfil privado limita quem pode ver fotografias, vídeos e publicações apenas a pessoas aprovadas — uma das formas mais simples de proteger a tua identidade digital." },
    { q:"O que é a identidade digital?", a:[{t:"A imagem e informação que uma pessoa constrói e partilha sobre si online",ok:true},{t:"Um documento de identificação físico",ok:false},{t:"O nome do dispositivo que usas",ok:false}], exp:"A identidade digital é o conjunto de informação, imagens e publicações que representam uma pessoa no mundo online." },
    { q:"É seguro usar exatamente a mesma foto de perfil e nome verdadeiro em todas as plataformas?", a:[{t:"Convém ponderar, pois facilita que alguém te identifique e localize em vários sítios",ok:true},{t:"Sim, é sempre totalmente seguro",ok:false},{t:"Só é arriscado em jogos, não em redes sociais",ok:false}], exp:"Usar sempre a mesma informação identificável em todas as plataformas pode facilitar que alguém junte informação sobre ti — vale a pena ponderar o que partilhas em cada uma." },
    { q:"Porque pedem as plataformas uma idade mínima para criar conta?", a:[{t:"Para proteger crianças mais novas de conteúdos e riscos inadequados para a sua idade",ok:true},{t:"Só para limitar o número de utilizadores",ok:false},{t:"Não tem qualquer relação com proteção de menores",ok:false}], exp:"As idades mínimas existem para proteger crianças mais novas de conteúdos, contactos e riscos que podem não ser adequados para a sua idade." },
    { q:"Podes ter identidades digitais diferentes em plataformas diferentes (por exemplo, um nome numa rede social e outro num jogo)?", a:[{t:"Sim, e isso pode ajudar a proteger a tua privacidade em cada contexto",ok:true},{t:"Não, tens de usar sempre exatamente o mesmo nome em todo o lado",ok:false},{t:"Não, isso é sempre proibido pelas plataformas",ok:false}], exp:"Usar informação diferente (como nomes ou fotos de perfil) em plataformas diferentes pode ajudar a proteger a tua privacidade, tornando mais difícil que alguém junte tudo sobre ti num único perfil." },
    { q:"A tua identidade digital é construída só por aquilo que tu publicas sobre ti próprio?", a:[{t:"Não, também é influenciada pelo que outras pessoas publicam ou dizem sobre ti",ok:true},{t:"Sim, só depende do que tu publicas",ok:false},{t:"Não tem qualquer relação com o que os outros publicam",ok:false}], exp:"A identidade digital não depende só do que publicamos sobre nós próprios — também é influenciada por fotografias, marcações e comentários que outras pessoas fazem sobre nós." },
    { q:"Devem os nomes de utilizador (nicknames) online revelar sempre dados pessoais, como o teu nome completo ou a tua morada?", a:[{t:"Não, é mais seguro escolher um nome de utilizador que não revele dados pessoais",ok:true},{t:"Sim, deve revelar sempre o máximo de informação possível",ok:false},{t:"Sim, mas só em jogos online",ok:false}], exp:"Escolher um nome de utilizador que não revele o teu nome completo, morada ou outros dados pessoais é uma forma simples de proteger a tua identidade digital." }
  ],
  privacidade: [
    { q:"O que significa respeitar a privacidade de outras pessoas online?", a:[{t:"Não partilhar fotos ou informações sobre elas sem autorização",ok:true},{t:"Publicar tudo o que sabes sobre os amigos, sem pedir",ok:false},{t:"Só é preciso respeitar a privacidade de desconhecidos",ok:false}], exp:"Respeitar a privacidade dos outros significa não partilhar fotos, vídeos ou informações pessoais deles sem a autorização deles." },
    { q:"Porque deves manter as tuas próprias contas privadas?", a:[{t:"Para controlar quem pode ver as tuas publicações e informações",ok:true},{t:"Não faz diferença nenhuma manter as contas privadas",ok:false},{t:"Só serve para teres menos seguidores",ok:false}], exp:"Manter as contas privadas dá-te controlo sobre quem vê o que publicas, protegendo a tua privacidade e segurança." },
    { q:"É correto partilhar uma conversa privada de um amigo sem lhe pedir autorização?", a:[{t:"Não, isso viola a privacidade e a confiança dessa pessoa",ok:true},{t:"Sim, se a conversa não for muito importante",ok:false},{t:"Sim, é sempre permitido partilhar conversas privadas",ok:false}], exp:"Partilhar conversas privadas sem autorização quebra a confiança e a privacidade da pessoa envolvida, mesmo que o conteúdo pareça inofensivo." },
    { q:"O que deves fazer antes de publicar uma foto de grupo com amigos?", a:[{t:"Confirmar se todos concordam em aparecer publicados",ok:true},{t:"Publicar imediatamente, sem perguntar a ninguém",ok:false},{t:"Só é preciso perguntar se a foto for feia",ok:false}], exp:"Perguntar a todos os presentes se concordam em ser publicados é uma forma simples de respeitar a privacidade de cada um." },
    { q:"A privacidade online aplica-se apenas a adultos?", a:[{t:"Não, é um direito de todas as pessoas, incluindo crianças",ok:true},{t:"Sim, só os adultos têm direito à privacidade",ok:false},{t:"Só se aplica a figuras públicas",ok:false}], exp:"A privacidade, tal como offline, é um direito que se aplica a todas as pessoas, independentemente da idade." },
    { q:"As definições de privacidade de uma conta ou rede social são sempre as mais seguras logo desde o início, sem precisares de as alterar?", a:[{t:"Nem sempre — vale a pena rever e ajustar as definições de privacidade de cada conta",ok:true},{t:"Sim, as definições padrão são sempre as mais seguras possíveis",ok:false},{t:"Não é possível alterar as definições de privacidade",ok:false}], exp:"Muitas aplicações e redes sociais não vêm configuradas com as opções mais privadas por predefinição — vale sempre a pena rever e ajustar as definições de privacidade." },
    { q:"Marcar (etiquetar) um amigo numa fotografia sem lhe perguntar antes é sempre inofensivo?", a:[{t:"Não, também pode revelar informação sobre essa pessoa sem o seu consentimento",ok:true},{t:"Sim, marcar alguém nunca tem qualquer consequência",ok:false},{t:"Sim, desde que a fotografia seja bonita",ok:false}], exp:"Marcar alguém numa fotografia pode ligar essa pessoa a um determinado local, momento ou grupo de pessoas — por isso, tal como partilhar uma foto, vale a pena pedir autorização antes." },
    { q:"A privacidade online aplica-se apenas às fotografias que publicas?", a:[{t:"Não, aplica-se a qualquer tipo de informação pessoal, incluindo textos, localização e conversas",ok:true},{t:"Sim, só se aplica a fotografias",ok:false},{t:"Sim, mas só a vídeos",ok:false}], exp:"A privacidade online abrange qualquer tipo de informação pessoal — fotografias, mas também textos, localização, conversas e muito mais." }
  ],
  contacto_desconhecidos: [
    { q:"O que deves fazer se receberes um pedido de amizade de um desconhecido nas redes sociais?", a:[{t:"Pensar bem, e evitar aceitar se não conheceres realmente a pessoa",ok:true},{t:"Aceitar sempre, quanto mais amigos melhor",ok:false},{t:"Aceitar apenas se o perfil tiver muitas fotos",ok:false}], exp:"Aceitar pedidos de desconhecidos aumenta o risco de contacto com pessoas com más intenções — o mais seguro é só aceitar quem realmente conheces." },
    { q:"O que deves fazer se um desconhecido online pedir fotografias tuas?", a:[{t:"Recusar e contar imediatamente a um adulto de confiança",ok:true},{t:"Enviar, se a pessoa insistir muito",ok:false},{t:"Enviar só se prometer não mostrar a mais ninguém",ok:false}], exp:"Nunca se deve enviar fotografias pessoais a desconhecidos online — o mais seguro é recusar e contar sempre a um adulto de confiança." },
    { q:"O que é o 'grooming' online?", a:[{t:"Quando um adulto tenta ganhar a confiança de uma criança online para a explorar",ok:true},{t:"Um tipo de jogo educativo",ok:false},{t:"Uma técnica de edição de fotografias",ok:false}], exp:"Grooming é quando um adulto se aproxima gradualmente de uma criança online, ganhando a sua confiança com más intenções — reconhecer os sinais e contar a um adulto é essencial." },
    { q:"Um desconhecido online pode não ser realmente quem diz ser?", a:[{t:"Sim, é possível criar perfis falsos com fotos e informações inventadas",ok:true},{t:"Não, todos os perfis online são sempre verdadeiros",ok:false},{t:"Só acontece em jogos, nunca em redes sociais",ok:false}], exp:"É possível criar perfis falsos, com fotos e idades inventadas, para enganar outras pessoas online — por isso é importante ter sempre cuidado com desconhecidos." },
    { q:"O que deve fazer uma criança se um contacto online insistir para guardar segredo dos pais sobre a conversa?", a:[{t:"Desconfiar e contar exatamente isso a um adulto de confiança",ok:true},{t:"Guardar segredo, como foi pedido",ok:false},{t:"Ignorar o pedido mas continuar a conversa sozinha",ok:false}], exp:"Pedir segredo é um sinal de alerta muito comum em situações perigosas online — deve ser sempre partilhado com um adulto de confiança, mesmo que pareça inofensivo." },
    { q:"É seguro combinar um encontro presencial com alguém que só conheces através da internet, mesmo levando um amigo?", a:[{t:"Não é recomendado — o mais seguro é falar sempre primeiro com um adulto de confiança",ok:true},{t:"Sim, é sempre seguro desde que não vás sozinho",ok:false},{t:"Sim, é sempre seguro se combinares num local público",ok:false}], exp:"Encontros presenciais com pessoas conhecidas apenas online envolvem sempre riscos, mesmo em locais públicos ou acompanhado — o mais seguro é falar sempre primeiro com um adulto de confiança." },
    { q:"Um desconhecido online que elogia muito uma criança e lhe oferece prendas pode ser um sinal de alerta?", a:[{t:"Sim, pode ser um sinal de tentativa de ganhar a confiança da criança com más intenções",ok:true},{t:"Não, elogios e prendas são sempre inofensivos",ok:false},{t:"Não, só é preciso ter cuidado se a pessoa pedir dinheiro",ok:false}], exp:"Elogios excessivos e prendas vindas de um desconhecido online podem ser uma forma de ganhar a confiança de uma criança antes de tentar algo prejudicial — deve ser sempre partilhado com um adulto de confiança." },
    { q:"É seguro aceitar um desconhecido só porque tens amigos em comum com ele numa rede social?", a:[{t:"Não necessariamente — ter amigos em comum não garante que a pessoa seja de confiança",ok:true},{t:"Sim, ter amigos em comum é sempre garantia de segurança",ok:false},{t:"Sim, mas só se o perfil tiver muitas fotografias",ok:false}], exp:"Ter amigos em comum não garante que um desconhecido seja de confiança — mesmo assim, vale a pena ter cuidado antes de aceitar pedidos de pessoas que não conheces pessoalmente." }
  ],
  direitos_digitais: [
    { q:"Desde quando é que a ONU reconhece que os direitos das crianças se aplicam também ao mundo digital?", a:[{t:"Desde 2021",ok:true},{t:"Desde 1989",ok:false},{t:"Ainda não são reconhecidos oficialmente",ok:false}], exp:"Em 2021, o Comité dos Direitos da Criança da ONU confirmou que todos os direitos da Convenção se aplicam ao ambiente digital — privacidade, proteção, expressão e educação incluídas." },
    { q:"Além de direitos, que outra responsabilidade têm os utilizadores da internet?", a:[{t:"Deveres, como usar a internet com responsabilidade e respeito por todos",ok:true},{t:"Nenhuma, só existem direitos online",ok:false},{t:"Só os adultos têm deveres online",ok:false}], exp:"Com os direitos digitais vêm também deveres: usar a internet de forma responsável, respeitando a privacidade e a segurança de todos." },
    { q:"O que resume melhor tudo o que aprendeste sobre cibersegurança?", a:[{t:"Pensar antes de agir, proteger os teus dados e pedir ajuda sempre que precisares",ok:true},{t:"Nunca usar a internet, é a única forma de estar seguro",ok:false},{t:"Confiar sempre em tudo o que aparece online",ok:false}], exp:"A cibersegurança resume-se a pensar antes de agir, proteger dados e palavras-passe, e pedir ajuda a um adulto sempre que algo parecer errado." },
    { q:"Os direitos digitais das crianças incluem proteção contra o quê?", a:[{t:"Ciberbullying, exploração de dados e conteúdos inadequados",ok:true},{t:"Apenas contra vírus informáticos",ok:false},{t:"Não incluem qualquer forma de proteção",ok:false}], exp:"Os direitos digitais das crianças incluem proteção contra ciberbullying, uso indevido de dados pessoais e exposição a conteúdos inadequados para a sua idade." },
    { q:"Porque é importante continuar a aprender sobre cibersegurança ao longo da vida?", a:[{t:"Porque a tecnologia e os riscos online mudam constantemente",ok:true},{t:"Não é importante, depois de aprender uma vez está resolvido para sempre",ok:false},{t:"Só é importante para quem trabalha em informática",ok:false}], exp:"A tecnologia evolui rapidamente e surgem novos riscos — por isso a cibersegurança é uma aprendizagem contínua, para todas as idades." },
    { q:"Como se chama o documento em que a ONU reconheceu, em 2021, os direitos das crianças no ambiente digital?", a:[{t:"Comentário Geral n.º 25, do Comité dos Direitos da Criança",ok:true},{t:"Declaração Universal da Internet",ok:false},{t:"Tratado Europeu de Cibersegurança",ok:false}], exp:"Em 2021, o Comité dos Direitos da Criança da ONU publicou o Comentário Geral n.º 25, confirmando que os direitos da Convenção sobre os Direitos da Criança se aplicam também ao ambiente digital." },
    { q:"Os direitos digitais das crianças incluem o direito à educação sobre segurança online?", a:[{t:"Sim, incluem o direito a ser informado e educado sobre como navegar em segurança",ok:true},{t:"Não, os direitos digitais só falam de proteção contra crimes",ok:false},{t:"Não, a educação digital não é considerada um direito",ok:false}], exp:"Os direitos digitais das crianças incluem também o direito à educação e à informação sobre como usar a tecnologia de forma segura e crítica." },
    { q:"Ter deveres online (como respeitar os outros) é incompatível com teres direitos online?", a:[{t:"Não, direitos e deveres andam sempre lado a lado",ok:true},{t:"Sim, só podes ter uma coisa ou a outra",ok:false},{t:"Sim, os deveres anulam sempre os direitos",ok:false}], exp:"Direitos e deveres online complementam-se: ao mesmo tempo que tens direito à privacidade e proteção, tens também o dever de respeitar a privacidade e a segurança dos outros." }
  ]
};
